version: "3.9"

networks:
  comics-api-net:
    external: false
    name: comics-api-net

services:
  db:
    image: postgres:13-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data/pgdata
    networks:
      - comics-api-net
    container_name: comics-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  comics-service:
    depends_on:
      - db
    networks:
      - comics-api-net
    container_name: comics-api
    image: mpcalzada/comics-api:1.0
    ports:
      - "80:80"

volumes:
  db-volume: