package com.mcalzada.service;

import com.mcalzada.model.entity.Comic;
import com.mcalzada.repository.ComicRepository;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * ComicService is a JEE Bean built over the service layer for the application. Performs domain operations within the controller, gateway and repositories
 *
 * @author Marco Calzada
 * @version 1.0
 */
@Service
public class ComicService
{

    private final ComicRepository comicRepository;

    /**
     * Service constructor autogenerated by springboot context
     *
     * @param comicRepository repository used to perform data-gather operations
     */
    @Autowired
    public ComicService(ComicRepository comicRepository)
    {
        this.comicRepository = comicRepository;
    }

    /**
     * Search a hero in the comics which participated.
     *
     * @param characterName Name of the character/hero looking for
     * @return List of comics where the hero participate. Empty list if none were found.
     */
    public List<Comic> searchComicsByCharacterName(String characterName)
    {
        return comicRepository.findComicsByCharactersName(characterName);
    }

    /**
     * Creates the provided comics in the configured repository
     *
     * @param comics List of comics to be created
     */
    public void createComics(List<Comic> comics)
    {
        comicRepository.saveAll(comics);
    }

}
